deploy-prod:
  stage: deploy
  image: roffe/kubectl
  script:
    - kubectl get pods
    - kubectl get all
    - kubectl get namespaces
  environment:
    name: production
    kubernetes:
      namespace: default
  only:
    - master
