deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  environment:
    name: production
  script:
    - kubectl version
    - echo $KUBECONFIG64 | base64 -d > $KUBECONFIG 
    - kubectl apply -f dvwa-dep.yml
