deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  environment:
    name: production
  script:
    - kubectl version
    - echo -n $KUBE_CONFIG | base64 -d > ./config
    - kubectl apply -f gitlab-runner-admin.yml 
    - kubectl get pods
    - kubectl get deployments
    - kubectl apply -f dvwa-dep.yml
variables:
#assign base64 encoded kubeconfig file (in GitLab UI) to variable
  KUBE_CONFIG: $KUBE_CONFIG64
