deploy:
   image:
     name: nginx:latest
     entrypoint: [""]
   script:
   - kubectl config get-contexts
   - kubectl config use-context kubernetes-admin@kubernetes
   - kubectl get pods
variables:
  KUBERNETES_NAMESPACE_OVERWRITE: ci-${CI_COMMIT_REF_SLUG}
